### Создание первого пользователя админа
POST http://localhost:80/users/add-root-user
Content-Type: application/json

{
  "username": "root",
  "password": "Super-puper-777"
}

### Создание пользователя
POST http://localhost:80/users/add
Content-Type: application/json

{
  "username": "root",
  "password": "Super-puper-777",
  "newUsername": "dirmir",
  "newPassword": "sdffdg#s@@2D"
}

### Создание пользователя админа суперадмином
POST http://localhost:80/users/add
Content-Type: application/json

{
  "username": "root",
  "password": "Super-puper-777",
  "newUsername": "dirmir3",
  "newPassword": "sdffdg#s@@2D",
  "newAdmin": "true"
}

### Провальное создание пользователя админа другим админом из-за недостатка прав
POST http://localhost:80/users/add
Content-Type: application/json

{
  "username": "dirmir3",
  "password": "sdffdg#s@@2D",
  "newUsername": "dirmir4",
  "newPassword": "sdffdg#s@@2D",
  "newAdmin": "true"
}

### создание пользователя обычным админом
POST http://localhost:80/users/add
Content-Type: application/json

{
  "username": "dirmir3",
  "password": "sdffdg#s@@2D",
  "newUsername": "dirmir4",
  "newPassword": "sdffdg#s@@2D"
}

### Попытка создания пользователя обычным админом без указания имени
POST http://localhost:80/users/add
Content-Type: application/json

{
  "username": "dirmir3",
  "password": "sdffdg#s@@2D",
  "newPassword": "sdffdg#s@@2D"
}

### Блокирование пользователя
POST http://localhost:80/users/block
Content-Type: application/json

{
  "username": "root",
  "password": "Super-puper-777",
  "blockedUsername": "dirmir"
}

### Разблокирование пользователя
POST http://localhost:80/users/unblock
Content-Type: application/json

{
  "username": "dirmir3",
  "password": "sdffdg#s@@2D",
  "unblockedUsername": "dirmir"
}

### Смена пароля пользователя админом
POST http://localhost:80/users/change-password
Content-Type: application/json

{
  "username": "dirmir3",
  "password": "sdffdg#s@@2D",
  "neededUsername": "dirmir",
  "newPassword": "32fasdfSDFfsd#"
}


### Неудачная попытка смены пароля пользователя другим юзером
POST http://localhost:80/users/change-password
Content-Type: application/json

{
  "username": "dirmir4",
  "password": "sdffdg#s@@2D",
  "neededUsername": "dirmir",
  "newPassword": "32fasdfSDFfsd#"
}

### Смена пароля пользователя самим юзером
POST http://localhost:80/users/change-password
Content-Type: application/json

{
  "username": "dirmir",
  "password": "32fasdfSDFfsd#",
  "neededUsername": "dirmir",
  "newPassword": "sdffdg#s@@2D"
}

### Пост нового лида.
POST http://localhost:80/leads/new
Content-Type: application/json

{
  "username": "dirmir",
  "password": "sdffdg#s@@2D",
  "name": "question",
  "sourceId": "yandex",
  "status": "new"
}

### Пост нового лида несуществующим юзером.
POST http://localhost:80/leads/new
Content-Type: application/json

{
  "username": "dirmir55",
  "password": "sdffdg#s@@2D",
  "name": "question",
  "sourceId": "yandex",
  "status": "new"
}

### Запрос своих лидов обычным юзером.
GET http://localhost:80/leads/get
Content-Type: application/json

{
  "username": "dirmir",
  "password": "sdffdg#s@@2D",
  "pageSize": "5",
  "pageNumber": "0",
  "filterStatus": {
    "0": "new",
    "1": "active"
  }
}

### Запрос своих лидов обычным юзером.
GET http://localhost:80/leads/get
Content-Type: application/json

{
  "username": "dirmir4",
  "password": "sdffdg#s@@2D",
  "pageSize": "5",
  "pageNumber": "0",
  "filterStatus": {
    "0": "new",
    "1": "active"
  }
}

### Запрос лидов админом.
GET http://localhost:80/leads/get
Content-Type: application/json

{
  "username": "dirmir3",
  "password": "sdffdg#s@@2D",
  "pageSize": "5",
  "pageNumber": "0",
  "filterUsers": {
    "0": "dirmir",
    "1": "dirmir4"
  },
  "filterStatus": {
    "0": "new",
    "1": "active"
  }
}

### Запрос лидов админом.
GET http://localhost:80/leads/get
Content-Type: application/json

{
  "username": "dirmir3",
  "password": "sdffdg#s@@2D",
  "pageSize": "5",
  "pageNumber": "0",
  "filterUsers": {
    "0": "dirmir3",
    "1": "dirmir4"
  },
  "filterStatus": {
    "0": "new",
    "1": "active"
  }
}






### Загрузите фикстуры путем запуска команды "make fixture"
### Запрос лидов обычным юзером без фильтра.
GET http://localhost:80/leads/get
Content-Type: application/json

{
  "username": "User_1",
  "password": "123456",
  "pageSize": "5",
  "pageNumber": "2"
}

### Запрос лидов обычным юзером с фильтром.
GET http://localhost:80/leads/get
Content-Type: application/json

{
  "username": "User_2",
  "password": "123456",
  "pageSize": "7",
  "pageNumber": "3",
  "filterStatus": {
    "0": "new",
    "1": "active"
  }
}

### Запрос лидов админом по 2 юзерам.
GET http://localhost:80/leads/get
Content-Type: application/json

{
  "username": "User_admin",
  "password": "123456",
  "pageSize": "5",
  "pageNumber": "0",
  "filterUsers": {
    "0": "User_3",
    "1": "User_4"
  }
}

### Запрос лидов админом по 2 юзерам и 2 статусам.
GET http://localhost:80/leads/get
Content-Type: application/json

{
  "username": "User_admin",
  "password": "123456",
  "pageSize": "5",
  "pageNumber": "0",
  "filterUsers": {
    "0": "User_3",
    "1": "User_4"
  },
  "filterStatus": {
    "0": "new",
    "1": "finished"
  }
}