add_root_user:
    path: /users/add-root-user
    controller: App\Controller\UserController::addFirstRootUser

add_user:
    path: /users/add
    controller: App\Controller\UserController::addUser

block_user:
    path: /users/block
    controller: App\Controller\UserController::blockUser

unblock_user:
    path: /users/unblock
    controller: App\Controller\UserController::unblockUser

change_user_password:
    path: /users/change-password
    controller: App\Controller\UserController::changeUserPassword